version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: contacts-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: contactsdb
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d contactsdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    container_name: contacts-backend
    build:
      context: ./backend
    ports:
      - 3000:8080
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=contactsdb;Username=user;Password=p@ssw0rd
      - SEED_ADMIN_EMAIL=admin@gmail.com
      - SEED_ADMIN_PASSWORD=adminpassword123
    depends_on:
      db:
        condition: service_healthy
